#!/usr/bin/python
#coding:utf8

'''
Usage:
    %(program)s <FILE or DIR>
Functions:
    Create a meta file for the input FILE or DIR
    and then auto open the meta file for edit
'''

import os, sys

default_meta='''
路径:
题名:
摘要:
标签:
'''

def load_meta(meta_string):
    meta={}
    for line in meta_string.strip().split():
        line=line.strip()
        if not line: continue
        key, val=line.split(':', 1)
        meta[key]=val.strip()
    return meta

def dump_meta(meta):
    ss=[]
    for k, v in meta.iteritems():
        ss.append('%s: %s' % (k, v))
    return '\n'.join(ss)+'\n'

if __name__=='__main__':
    program=sys.argv[0]

    if len(sys.argv) != 2:
        print >>sys.stderr, globals()['__doc__'] % locals()
        sys.exit(1)
    
    fp=sys.argv[1]
    if os.path.isfile(fp):
        pass
    elif os.path.isdir(fp):
        if os.path.dirname(fp)!=fp:
            fp=os.path.dirname(fp)
    else:
        print >>sys.stderr, 'bad input:', fp
        
    fp_meta=fp+'.meta.txt'

    print 'Meta File Path:', fp_meta

    if os.path.isfile(fp_meta):
        with open(fp_meta) as f: 
            txt_meta=f.read()
            meta=load_meta(txt_meta)
    else:
        meta=load_meta(default_meta)


    print dump_meta(meta)

